/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface PyCodeblock {
    'code': string;
    'filename': string;
  }
  interface PyCodeblockAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'filename'?: string;
    'onCodeblockMaximized'?: (event: CustomEvent) => void;
    'onCodeblockUnmaximized'?: (event: CustomEvent) => void;
  }

  interface PyGraphOverview {
    'data': OverviewData;
  }
  interface PyGraphOverviewAttributes extends StencilHTMLAttributes {
    'data'?: OverviewData;
  }

  interface PyNavigationBar {
    'current': string;
  }
  interface PyNavigationBarAttributes extends StencilHTMLAttributes {
    'current'?: string;
    'onBackEvent'?: (event: CustomEvent) => void;
    'onHomeEvent'?: (event: CustomEvent) => void;
    'onNextEvent'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PyCodeblock': Components.PyCodeblock;
    'PyGraphOverview': Components.PyGraphOverview;
    'PyNavigationBar': Components.PyNavigationBar;
  }

  interface StencilIntrinsicElements {
    'py-codeblock': Components.PyCodeblockAttributes;
    'py-graph-overview': Components.PyGraphOverviewAttributes;
    'py-navigation-bar': Components.PyNavigationBarAttributes;
  }


  interface HTMLPyCodeblockElement extends Components.PyCodeblock, HTMLStencilElement {}
  var HTMLPyCodeblockElement: {
    prototype: HTMLPyCodeblockElement;
    new (): HTMLPyCodeblockElement;
  };

  interface HTMLPyGraphOverviewElement extends Components.PyGraphOverview, HTMLStencilElement {}
  var HTMLPyGraphOverviewElement: {
    prototype: HTMLPyGraphOverviewElement;
    new (): HTMLPyGraphOverviewElement;
  };

  interface HTMLPyNavigationBarElement extends Components.PyNavigationBar, HTMLStencilElement {}
  var HTMLPyNavigationBarElement: {
    prototype: HTMLPyNavigationBarElement;
    new (): HTMLPyNavigationBarElement;
  };

  interface HTMLElementTagNameMap {
    'py-codeblock': HTMLPyCodeblockElement
    'py-graph-overview': HTMLPyGraphOverviewElement
    'py-navigation-bar': HTMLPyNavigationBarElement
  }

  interface ElementTagNameMap {
    'py-codeblock': HTMLPyCodeblockElement;
    'py-graph-overview': HTMLPyGraphOverviewElement;
    'py-navigation-bar': HTMLPyNavigationBarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
