os:
    - linux
language: node_js
node_js: stable
dist: bionic
sudo: required
addons:
    apt:
        sources:
            - google-chrome
            - sourceline: 'deb http://deb.debian.org/debian stretch main'
              key_url: 'https://ftp-master.debian.org/keys/archive-key-8.asc'
        packages:
            - google-chrome-stable
            - graphviz
    sonarcloud:
        organization: 'pytheas-tools'
        token:
            secure: 'fm3A7MJufehMUvlFqVxGSumGJvpvOflM1FtCb4VGLeAXnZ0jQwd8ccbkNd2d0tZZia8GAVyya9gcsU+OGU/VEuyRg6BkK4cPw2LOAtk7uEEccLj7/LRWQDEK0aBMrnL5tlgpEvPz+WZeivOXXkbVuDg79cOl7irYW5hCx9Ng7Lpxd0Ry/PATdichuAa4FaNVYTV5cEUpz3jVTUjmg+UxQuPKCrkTIqqGV+v1iwcWSNjr0jrepMEaydDakxctkTqxekn8vMLeoG7R3udbRTdMU5qJqrI+2pJYXo/5hRjrKhUHa3Pai9RtRxufe3jN6EA7lbjIF06fFmgkwVsLT1lx8xQnaYD/jNtprkrR83B1QmKgh+Vl/JwQK4PPlCFKPyRfQUqQkq6W0oxumaezBzzXdPIf2emOUqaQBNT2RRkwZcSLnYaCzmZr7uCNKUORRnCkmY7IezYc+C8RTyY0FFXCj7mRjDLYMC9qVR+FO+oKthiJ3sIFhBSD6Nf4nXIgO0gt6losvuWBdlmvdxyftBlq2d8svOe+6YIuDziGiXK/K1i4bn6dsGlJSn8Jv4fbyyOrfeMEG0YLyPNCVbx59jvn47htOcfQTawJKGWYuT1NdMyKOLn/8MCnEbc5pYHhtHj6TnBhFzMULi2UKcq+R1pJMF1qd0GjamvnjnSWM4bt514='
cache:
    # Caches $HOME/.npm when npm ci is default script command
    # Caches node_modules in all other cases
    npm: true
    directories:
        # we also need to cache folder with Cypress binary
        - ~/.cache

jobs:
    include:
        - stage: testing web components
          install:
              - npm install npm@latest -g
              - cd packages/pytheas-components
              - npm ci
          script:
              - npm run test
        - stage: unit testing app
          install:
              - npm install npm@latest -g
              - echo "\n**********\nBUILDING STATIC DEPENDENCIES\n**********\n"
              - cd packages/pytheas-ui-static-dependencies
              - npm ci
              - npm run build:prod
              - cd ../pytheas-ui
              - npm ci
              - mkdir output
              - mkdir output/scripts
              - npm run build-browser-dependencies
          script:
              - npm run test:unit
              - sonar-scanner
        - stage: e2e testing app
          install:
              - npm install npm@latest -g
              - echo "\n**********\nBUILDING STATIC DEPENDENCIES\n**********\n"
              - cd packages/pytheas-ui-static-dependencies
              - npm ci
              - echo "\n**********\nBUILDING WEB COMPONENTS\n**********\n"
              - cd ../pytheas-components
              - npm ci
              - npm run build:prod
              - echo -e "\n**********\nBUILD PROD APP\n**********\n"
              - cd ../pytheas-ui
              - npm ci
              - mkdir output
              - mkdir output/web-components
              - mkdir output/scripts
              - npm run build
          script:
              - npm run test:e2e
        - stage: build prod app
          install:
              - npm install npm@latest -g
              - cd packages/pytheas-components
              - npm ci
          script:
              - echo "\n**********\nBUILDING WEB COMPONENTS\n**********\n"
              - cd ../pytheas-components
              - npm run build:prod
              - cd ../pytheas-ui
              - npm ci
              - mkdir output
              - mkdir output/web-components
              - mkdir output/scripts
              - npm run build-browser-dependencies
              - echo -e "\n**********\nBUILD PROD APP\n**********\n"
              - npm run build
              - npm run copy-wc
              - echo -e "\n**********\nBUILD DOC\n**********\n"
              - cd ../pytheas-documentation
              - npm ci
              - npm run madge
              - npm run docs:build
              - cp -R src/.vuepress/dist ../pytheas-ui/output/contributors-documentation
              - cd ../pytheas-ui
              - npm run doc:code
              - cp -R code-documentation ./output/code-documentation
              - echo -e "\n**********\nDEPLOY\n**********\n"
              - bash ./deploy.sh
branches:
    only:
        - develop
env:
    global:
        - GH_REF: github.com/pytheas-tools/pytheas.git
        - secure: I/jqJ/T6X79mmeKdLxEBXBxX+nhf/nlYZ5ConuJ5s22unQt2pfbWoLe0bAPPawVQ0oK/DhQkVG7coKi7AsQWpOUqBu0j1vvNVbNn8w8F1p3n6bjPM9jPee4JTjOHjsMz8aUWzWq2uz9z118TwrCglep/2dz0qxt/8rfuvBJFah+xT4tZoT8TfUsK8bEz5gZvwlHuPCZIOfeWaEwSO8rIDgF4b9uiaGSSBNSjqAz/Wpr09Bty1bj90SNjYkRiBaUcGnlpuLZEZNEJwx72sZ+gRuAu4lta7/BqXFTj8reqIvUo8ZmkkJWQY1xRGotkbUA7R0nIlqcUemNDCVHukQEf+muTxa2EWjZMYcrox+W+0yIsSJSnMVWDFZznMZ317rctvml8uGG+VLJx7RExiOQBKlYbKaHe1wzeUo9uRQXy6YgAIKtWwaQkCGRPdhTipl9Kv7t0bSPhzPj2bIK4WNJCUN2Jwn4Ri8u+hgikEv4KnqEH+NMo7438uPPtkLniT7rBoOp+5dvZfvczoq9IbqwktMpq0CcoBygxca7bPCNUdZcj+ts19evwymi4rywfSgzo7yL3BM/tNTjrSopaNW3naNtZFf45cenDwydpi+yNKG6ERwcICFNbSuecME/aTo1YdT9ZUusuussFH8yY5gqo3L3n4igF+fQGWWEuiZVVsWM=
