os:
    - linux
language: node_js
node_js: 'stable'

dist: trusty
sudo: required

addons:
    firefox: latest
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable fluxbox

before_script:
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - sleep 3
    - fluxbox >/dev/null 2>&1 &

before_install:
    - stty cols 80
install:
    - npm install npm@latest -g
    - cd packages/pytheas-ui
    - npm ci
script:
    - npm run test-wc
    - npm run test:e2e
branches:
    only:
        - develop
