os:
    - linux
language: node_js
node_js:
    - '10'
install:
    - npm install npm@latest -g
    - cd packages/pytheas-ui
    - npm ci
script:
    - npm run test-wc
    - npm run test:e2e
branches:
    only:
        - develop
