version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.0
        steps:
            - checkout
            - run: cd packages/pytheas-documentation && npm ci && npm run madge
