version: 2
jobs:
    build:
        docker:
            - image: circleci/node:7.10
        steps:
            - checkout
            - run: echo "hello world"
            - cd packages/pytheas-documentation
            - npm i
            - npm run madge
