version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.0
        steps:
            - checkout
            - run: sudo apt-get update && sudo apt-get install -y graphviz
            - run: cat /etc/apt/sources.list
            - run: cd packages/pytheas-documentation && npm ci && npm run madge
