/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface PyCodeblock {
    'code': string;
    'filename': string;
  }
  interface PyCodeblockAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'filename'?: string;
  }

  interface MyComponent2 {
    'first': string;
    'last': string;
  }
  interface MyComponent2Attributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PyCodeblock': Components.PyCodeblock;
    'MyComponent2': Components.MyComponent2;
  }

  interface StencilIntrinsicElements {
    'py-codeblock': Components.PyCodeblockAttributes;
    'my-component2': Components.MyComponent2Attributes;
  }


  interface HTMLPyCodeblockElement extends Components.PyCodeblock, HTMLStencilElement {}
  var HTMLPyCodeblockElement: {
    prototype: HTMLPyCodeblockElement;
    new (): HTMLPyCodeblockElement;
  };

  interface HTMLMyComponent2Element extends Components.MyComponent2, HTMLStencilElement {}
  var HTMLMyComponent2Element: {
    prototype: HTMLMyComponent2Element;
    new (): HTMLMyComponent2Element;
  };

  interface HTMLElementTagNameMap {
    'py-codeblock': HTMLPyCodeblockElement
    'my-component2': HTMLMyComponent2Element
  }

  interface ElementTagNameMap {
    'py-codeblock': HTMLPyCodeblockElement;
    'my-component2': HTMLMyComponent2Element;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
