/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface PyCodeblock {
    'first': string;
    'last': string;
  }
  interface PyCodeblockAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PyCodeblock': Components.PyCodeblock;
  }

  interface StencilIntrinsicElements {
    'py-codeblock': Components.PyCodeblockAttributes;
  }


  interface HTMLPyCodeblockElement extends Components.PyCodeblock, HTMLStencilElement {}
  var HTMLPyCodeblockElement: {
    prototype: HTMLPyCodeblockElement;
    new (): HTMLPyCodeblockElement;
  };

  interface HTMLElementTagNameMap {
    'py-codeblock': HTMLPyCodeblockElement
  }

  interface ElementTagNameMap {
    'py-codeblock': HTMLPyCodeblockElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
